### ISSUE TITLE
Can not create QR code with more than 2331 characters

### ISSUE THREAD

**Issue by xpaulnim** [sabi-h/qpyr#15]
```python
>>> from qpyr import main
>>> main("a" * 2331)
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])
>>> main("a" * 2332)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/qpyr/qpyr/main.py", line 6, in main
    version, binary_str = encode(data, ecl=ecl)
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/qpyr/qpyr/encode.py", line 111, in encode
    version = get_best_version(data_segment, mode, ecl)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/qpyr/qpyr/encode.py", line 71, in get_best_version
    raise ValueError("Data too long")
ValueError: Data too long
>>> 
```

**Comment by sabi-h** [comment]
On this website you can go upto 2953 characters: https://www.nayuki.io/page/qr-code-generator-library.
<img width="799" alt="Screenshot 2024-08-02 at 17 06 32" src="https://github.com/user-attachments/assets/a0599804-85f8-441a-9796-836d54b861a6">

The error is due to upper limit of QR Codes, and the package doesn't support optimisation yet. This is why this package only allows maximum of 2331 characters and Nayuki's website supports 2953.

**Comment by nayuki** [comment]
Still, my library only supports different levels of optimization.

The Python language port only optimizes to the extent of choosing one segment type for the entire text data.

Meanwhile, the Java port and a web page demo ( https://www.nayuki.io/page/optimal-text-segmentation-for-qr-codes ) can perform the full optimization.

**Comment by nayuki** [comment]
@xpaulnim The limit of 2331 characters is due to the [default error correction level](https://github.com/sabi-h/qpyr/blob/33d09fd323ce24b159de6ba0ddb17422bafa629b/qpyr/main.py#L6) of M.

If you want to encode up to 2953 characters, use error correction level L, like this:

```python
>>> from qpyr import main
>>> main("a" * 2953, ecl="L")
```
